/**
 * This class is generated by jOOQ
 */
package com.derekprovance.data.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Incomes implements Serializable {

	private static final long serialVersionUID = -276145560;

	private Integer   id;
	private Integer   userId;
	private String    source;
	private Long      value;
	private String    cycleUnit;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Date      expiredOn;

	public Incomes() {}

	public Incomes(Incomes value) {
		this.id = value.id;
		this.userId = value.userId;
		this.source = value.source;
		this.value = value.value;
		this.cycleUnit = value.cycleUnit;
		this.createdAt = value.createdAt;
		this.updatedAt = value.updatedAt;
		this.expiredOn = value.expiredOn;
	}

	public Incomes(
		Integer   id,
		Integer   userId,
		String    source,
		Long      value,
		String    cycleUnit,
		Timestamp createdAt,
		Timestamp updatedAt,
		Date      expiredOn
	) {
		this.id = id;
		this.userId = userId;
		this.source = source;
		this.value = value;
		this.cycleUnit = cycleUnit;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.expiredOn = expiredOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Long getValue() {
		return this.value;
	}

	public void setValue(Long value) {
		this.value = value;
	}

	public String getCycleUnit() {
		return this.cycleUnit;
	}

	public void setCycleUnit(String cycleUnit) {
		this.cycleUnit = cycleUnit;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getExpiredOn() {
		return this.expiredOn;
	}

	public void setExpiredOn(Date expiredOn) {
		this.expiredOn = expiredOn;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Incomes (");

		sb.append(id);
		sb.append(", ").append(userId);
		sb.append(", ").append(source);
		sb.append(", ").append(value);
		sb.append(", ").append(cycleUnit);
		sb.append(", ").append(createdAt);
		sb.append(", ").append(updatedAt);
		sb.append(", ").append(expiredOn);

		sb.append(")");
		return sb.toString();
	}
}
