/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db.tables.daos;


import com.derekprovance.plutos.data.db.tables.Users;
import com.derekprovance.plutos.data.db.tables.records.UsersRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, com.derekprovance.plutos.data.db.tables.pojos.Users, Integer> {

	/**
	 * Create a new UsersDao without any configuration
	 */
	public UsersDao() {
		super(Users.USERS, com.derekprovance.plutos.data.db.tables.pojos.Users.class);
	}

	/**
	 * Create a new UsersDao with an attached configuration
	 */
	public UsersDao(Configuration configuration) {
		super(Users.USERS, com.derekprovance.plutos.data.db.tables.pojos.Users.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.derekprovance.plutos.data.db.tables.pojos.Users object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchById(Integer... values) {
		return fetch(Users.USERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.derekprovance.plutos.data.db.tables.pojos.Users fetchOneById(Integer value) {
		return fetchOne(Users.USERS.ID, value);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByFirstName(String... values) {
		return fetch(Users.USERS.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByLastName(String... values) {
		return fetch(Users.USERS.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByEmail(String... values) {
		return fetch(Users.USERS.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>pocket_change IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByPocketChange(Long... values) {
		return fetch(Users.USERS.POCKET_CHANGE, values);
	}

	/**
	 * Fetch records that have <code>witholdings IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByWitholdings(Long... values) {
		return fetch(Users.USERS.WITHOLDINGS, values);
	}

	/**
	 * Fetch records that have <code>deductions IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByDeductions(Long... values) {
		return fetch(Users.USERS.DEDUCTIONS, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByCreatedAt(Timestamp... values) {
		return fetch(Users.USERS.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>updated_at IN (values)</code>
	 */
	public List<com.derekprovance.plutos.data.db.tables.pojos.Users> fetchByUpdatedAt(Timestamp... values) {
		return fetch(Users.USERS.UPDATED_AT, values);
	}
}
