/**
 * This class is generated by jOOQ
 */
package com.derekprovance.data.db.tables;


import com.derekprovance.data.db.Keys;
import com.derekprovance.data.db.ProjectPlutos;
import com.derekprovance.data.db.tables.records.ExpendituresRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Expenditures extends TableImpl<ExpendituresRecord> {

	private static final long serialVersionUID = -850500440;

	/**
	 * The reference instance of <code>project_plutos.expenditures</code>
	 */
	public static final Expenditures EXPENDITURES = new Expenditures();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExpendituresRecord> getRecordType() {
		return ExpendituresRecord.class;
	}

	/**
	 * The column <code>project_plutos.expenditures.id</code>.
	 */
	public final TableField<ExpendituresRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>project_plutos.expenditures.user_id</code>.
	 */
	public final TableField<ExpendituresRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>project_plutos.expenditures.name</code>.
	 */
	public final TableField<ExpendituresRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>project_plutos.expenditures.value</code>.
	 */
	public final TableField<ExpendituresRecord, Long> VALUE = createField("value", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.type</code>.
	 */
	public final TableField<ExpendituresRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.cycle_unit</code>.
	 */
	public final TableField<ExpendituresRecord, String> CYCLE_UNIT = createField("cycle_unit", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.cycle_amt</code>.
	 */
	public final TableField<ExpendituresRecord, Integer> CYCLE_AMT = createField("cycle_amt", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.created_at</code>.
	 */
	public final TableField<ExpendituresRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.updated_at</code>.
	 */
	public final TableField<ExpendituresRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>project_plutos.expenditures.expired_on</code>.
	 */
	public final TableField<ExpendituresRecord, Integer> EXPIRED_ON = createField("expired_on", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>project_plutos.expenditures</code> table reference
	 */
	public Expenditures() {
		this("expenditures", null);
	}

	/**
	 * Create an aliased <code>project_plutos.expenditures</code> table reference
	 */
	public Expenditures(String alias) {
		this(alias, EXPENDITURES);
	}

	private Expenditures(String alias, Table<ExpendituresRecord> aliased) {
		this(alias, aliased, null);
	}

	private Expenditures(String alias, Table<ExpendituresRecord> aliased, Field<?>[] parameters) {
		super(alias, ProjectPlutos.PROJECT_PLUTOS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ExpendituresRecord, Integer> getIdentity() {
		return Keys.IDENTITY_EXPENDITURES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ExpendituresRecord> getPrimaryKey() {
		return Keys.KEY_EXPENDITURES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ExpendituresRecord>> getKeys() {
		return Arrays.<UniqueKey<ExpendituresRecord>>asList(Keys.KEY_EXPENDITURES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ExpendituresRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ExpendituresRecord, ?>>asList(Keys.EXPENDITURES_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Expenditures as(String alias) {
		return new Expenditures(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Expenditures rename(String name) {
		return new Expenditures(name, null);
	}
}
