/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

	private static final long serialVersionUID = 1589078958;

	private Integer   id;
	private String    firstName;
	private String    lastName;
	private String    email;
	private Long      pocketChange;
	private Long      witholdings;
	private Long      deductions;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Users() {}

	public Users(Users value) {
		this.id = value.id;
		this.firstName = value.firstName;
		this.lastName = value.lastName;
		this.email = value.email;
		this.pocketChange = value.pocketChange;
		this.witholdings = value.witholdings;
		this.deductions = value.deductions;
		this.createdAt = value.createdAt;
		this.updatedAt = value.updatedAt;
	}

	public Users(
		Integer   id,
		String    firstName,
		String    lastName,
		String    email,
		Long      pocketChange,
		Long      witholdings,
		Long      deductions,
		Timestamp createdAt,
		Timestamp updatedAt
	) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.pocketChange = pocketChange;
		this.witholdings = witholdings;
		this.deductions = deductions;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getPocketChange() {
		return this.pocketChange;
	}

	public void setPocketChange(Long pocketChange) {
		this.pocketChange = pocketChange;
	}

	public Long getWitholdings() {
		return this.witholdings;
	}

	public void setWitholdings(Long witholdings) {
		this.witholdings = witholdings;
	}

	public Long getDeductions() {
		return this.deductions;
	}

	public void setDeductions(Long deductions) {
		this.deductions = deductions;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Users (");

		sb.append(id);
		sb.append(", ").append(firstName);
		sb.append(", ").append(lastName);
		sb.append(", ").append(email);
		sb.append(", ").append(pocketChange);
		sb.append(", ").append(witholdings);
		sb.append(", ").append(deductions);
		sb.append(", ").append(createdAt);
		sb.append(", ").append(updatedAt);

		sb.append(")");
		return sb.toString();
	}
}
