/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db;


import com.derekprovance.plutos.data.db.tables.Expenditures;
import com.derekprovance.plutos.data.db.tables.Incomes;
import com.derekprovance.plutos.data.db.tables.SchemaVersion;
import com.derekprovance.plutos.data.db.tables.Users;
import com.derekprovance.plutos.data.db.tables.records.ExpendituresRecord;
import com.derekprovance.plutos.data.db.tables.records.IncomesRecord;
import com.derekprovance.plutos.data.db.tables.records.SchemaVersionRecord;
import com.derekprovance.plutos.data.db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>project_plutos</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<ExpendituresRecord, Integer> IDENTITY_EXPENDITURES = Identities0.IDENTITY_EXPENDITURES;
	public static final Identity<IncomesRecord, Integer> IDENTITY_INCOMES = Identities0.IDENTITY_INCOMES;
	public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<ExpendituresRecord> KEY_EXPENDITURES_PRIMARY = UniqueKeys0.KEY_EXPENDITURES_PRIMARY;
	public static final UniqueKey<IncomesRecord> KEY_INCOMES_PRIMARY = UniqueKeys0.KEY_INCOMES_PRIMARY;
	public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = UniqueKeys0.KEY_SCHEMA_VERSION_PRIMARY;
	public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<ExpendituresRecord, Integer> IDENTITY_EXPENDITURES = createIdentity(Expenditures.EXPENDITURES, Expenditures.EXPENDITURES.ID);
		public static Identity<IncomesRecord, Integer> IDENTITY_INCOMES = createIdentity(Incomes.INCOMES, Incomes.INCOMES.ID);
		public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<ExpendituresRecord> KEY_EXPENDITURES_PRIMARY = createUniqueKey(Expenditures.EXPENDITURES, Expenditures.EXPENDITURES.ID);
		public static final UniqueKey<IncomesRecord> KEY_INCOMES_PRIMARY = createUniqueKey(Incomes.INCOMES, Incomes.INCOMES.ID);
		public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = createUniqueKey(SchemaVersion.SCHEMA_VERSION, SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
		public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, Users.USERS.ID);
	}
}
