/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db;


import com.derekprovance.plutos.data.db.tables.Expenditures;
import com.derekprovance.plutos.data.db.tables.Incomes;
import com.derekprovance.plutos.data.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in project_plutos
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table project_plutos.expenditures
	 */
	public static final Expenditures EXPENDITURES = com.derekprovance.plutos.data.db.tables.Expenditures.EXPENDITURES;

	/**
	 * The table project_plutos.incomes
	 */
	public static final Incomes INCOMES = com.derekprovance.plutos.data.db.tables.Incomes.INCOMES;

	/**
	 * The table project_plutos.users
	 */
	public static final Users USERS = com.derekprovance.plutos.data.db.tables.Users.USERS;
}
