/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db.tables.records;


import com.derekprovance.plutos.data.db.tables.Expenditures;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpendituresRecord extends UpdatableRecordImpl<ExpendituresRecord> implements Record10<Integer, Integer, String, Long, String, String, Integer, Timestamp, Timestamp, Integer> {

	private static final long serialVersionUID = 812469364;

	/**
	 * Setter for <code>project_plutos.expenditures.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.value</code>.
	 */
	public void setValue(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.value</code>.
	 */
	public Long getValue() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.type</code>.
	 */
	public void setType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.type</code>.
	 */
	public String getType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.cycle_unit</code>.
	 */
	public void setCycleUnit(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.cycle_unit</code>.
	 */
	public String getCycleUnit() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.cycle_amt</code>.
	 */
	public void setCycleAmt(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.cycle_amt</code>.
	 */
	public Integer getCycleAmt() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>project_plutos.expenditures.expired_on</code>.
	 */
	public void setExpiredOn(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>project_plutos.expenditures.expired_on</code>.
	 */
	public Integer getExpiredOn() {
		return (Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Long, String, String, Integer, Timestamp, Timestamp, Integer> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Long, String, String, Integer, Timestamp, Timestamp, Integer> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Expenditures.EXPENDITURES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Expenditures.EXPENDITURES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Expenditures.EXPENDITURES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return Expenditures.EXPENDITURES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Expenditures.EXPENDITURES.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Expenditures.EXPENDITURES.CYCLE_UNIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Expenditures.EXPENDITURES.CYCLE_AMT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Expenditures.EXPENDITURES.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Expenditures.EXPENDITURES.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Expenditures.EXPENDITURES.EXPIRED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCycleUnit();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getCycleAmt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getExpiredOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value4(Long value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value5(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value6(String value) {
		setCycleUnit(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value7(Integer value) {
		setCycleAmt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value8(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value9(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord value10(Integer value) {
		setExpiredOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExpendituresRecord values(Integer value1, Integer value2, String value3, Long value4, String value5, String value6, Integer value7, Timestamp value8, Timestamp value9, Integer value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExpendituresRecord
	 */
	public ExpendituresRecord() {
		super(Expenditures.EXPENDITURES);
	}

	/**
	 * Create a detached, initialised ExpendituresRecord
	 */
	public ExpendituresRecord(Integer id, Integer userId, String name, Long value, String type, String cycleUnit, Integer cycleAmt, Timestamp createdAt, Timestamp updatedAt, Integer expiredOn) {
		super(Expenditures.EXPENDITURES);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, name);
		setValue(3, value);
		setValue(4, type);
		setValue(5, cycleUnit);
		setValue(6, cycleAmt);
		setValue(7, createdAt);
		setValue(8, updatedAt);
		setValue(9, expiredOn);
	}
}
