/**
 * This class is generated by jOOQ
 */
package com.derekprovance.plutos.data.db.tables.records;


import com.derekprovance.plutos.data.db.tables.Incomes;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncomesRecord extends UpdatableRecordImpl<IncomesRecord> implements Record8<Integer, Integer, String, Long, String, Timestamp, Timestamp, Date> {

	private static final long serialVersionUID = -456599297;

	/**
	 * Setter for <code>project_plutos.incomes.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>project_plutos.incomes.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>project_plutos.incomes.source</code>.
	 */
	public void setSource(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.source</code>.
	 */
	public String getSource() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>project_plutos.incomes.value</code>.
	 */
	public void setValue(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.value</code>.
	 */
	public Long getValue() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>project_plutos.incomes.cycle_unit</code>.
	 */
	public void setCycleUnit(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.cycle_unit</code>.
	 */
	public String getCycleUnit() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>project_plutos.incomes.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>project_plutos.incomes.updated_at</code>.
	 */
	public void setUpdatedAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.updated_at</code>.
	 */
	public Timestamp getUpdatedAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>project_plutos.incomes.expired_on</code>.
	 */
	public void setExpiredOn(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>project_plutos.incomes.expired_on</code>.
	 */
	public Date getExpiredOn() {
		return (Date) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, Long, String, Timestamp, Timestamp, Date> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, Long, String, Timestamp, Timestamp, Date> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Incomes.INCOMES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Incomes.INCOMES.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Incomes.INCOMES.SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return Incomes.INCOMES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Incomes.INCOMES.CYCLE_UNIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Incomes.INCOMES.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Incomes.INCOMES.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return Incomes.INCOMES.EXPIRED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCycleUnit();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getExpiredOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value3(String value) {
		setSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value4(Long value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value5(String value) {
		setCycleUnit(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value6(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value7(Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord value8(Date value) {
		setExpiredOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IncomesRecord values(Integer value1, Integer value2, String value3, Long value4, String value5, Timestamp value6, Timestamp value7, Date value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IncomesRecord
	 */
	public IncomesRecord() {
		super(Incomes.INCOMES);
	}

	/**
	 * Create a detached, initialised IncomesRecord
	 */
	public IncomesRecord(Integer id, Integer userId, String source, Long value, String cycleUnit, Timestamp createdAt, Timestamp updatedAt, Date expiredOn) {
		super(Incomes.INCOMES);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, source);
		setValue(3, value);
		setValue(4, cycleUnit);
		setValue(5, createdAt);
		setValue(6, updatedAt);
		setValue(7, expiredOn);
	}
}
