/**
 * This class is generated by jOOQ
 */
package com.derekprovance.data.db.tables.daos;


import com.derekprovance.data.db.tables.Incomes;
import com.derekprovance.data.db.tables.records.IncomesRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncomesDao extends DAOImpl<IncomesRecord, com.derekprovance.data.db.tables.pojos.Incomes, Integer> {

	/**
	 * Create a new IncomesDao without any configuration
	 */
	public IncomesDao() {
		super(Incomes.INCOMES, com.derekprovance.data.db.tables.pojos.Incomes.class);
	}

	/**
	 * Create a new IncomesDao with an attached configuration
	 */
	public IncomesDao(Configuration configuration) {
		super(Incomes.INCOMES, com.derekprovance.data.db.tables.pojos.Incomes.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.derekprovance.data.db.tables.pojos.Incomes object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchById(Integer... values) {
		return fetch(Incomes.INCOMES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.derekprovance.data.db.tables.pojos.Incomes fetchOneById(Integer value) {
		return fetchOne(Incomes.INCOMES.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByUserId(Integer... values) {
		return fetch(Incomes.INCOMES.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>source IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchBySource(String... values) {
		return fetch(Incomes.INCOMES.SOURCE, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByValue(Long... values) {
		return fetch(Incomes.INCOMES.VALUE, values);
	}

	/**
	 * Fetch records that have <code>cycle_unit IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByCycleUnit(String... values) {
		return fetch(Incomes.INCOMES.CYCLE_UNIT, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByCreatedAt(Timestamp... values) {
		return fetch(Incomes.INCOMES.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>updated_at IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByUpdatedAt(Timestamp... values) {
		return fetch(Incomes.INCOMES.UPDATED_AT, values);
	}

	/**
	 * Fetch records that have <code>expired_on IN (values)</code>
	 */
	public List<com.derekprovance.data.db.tables.pojos.Incomes> fetchByExpiredOn(Date... values) {
		return fetch(Incomes.INCOMES.EXPIRED_ON, values);
	}
}
